version: '3.6'

services: 
  wordpress:
    image: wordpress:5.5-php7.2-fpm
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    container_name: ${APP_NAME}-wp
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TABLE_PREFIX: ${DB_TABLE_PREFIX}
    volumes:
      - ../.docker/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../web:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../.docker/nginx/default.conf:/tmp/default.template
      - ../.docker/certs:/etc/certs
      - ../web:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
